# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <user_name>
  password: <password>
  host: localhost
  #socket: /var/run/mysqld/mysqld.sock   # Use this line if you are using a UNIX socket
  port: 3306

development:
  <<: *default
  database: OpenERP-Ruby-development

production:
  <<: *default
  database: OpenERP-Ruby
  username: <your_db_username>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
